local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.colorcolumn = "80"
opt.cursorline = true
opt.expandtab = true
opt.ignorecase = true
opt.lazyredraw = true
opt.linebreak = true
opt.mouse = ""
opt.number = true
opt.relativenumber = true
opt.shiftwidth = 2
opt.showmatch = true
opt.smartcase = true
opt.swapfile = false
opt.tabstop = 2
opt.termguicolors = true
opt.timeout = false
opt.undodir = "~/.config/nvim/undo"
opt.undofile = true
